# Generated by Django 2.2.6 on 2022-10-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'followers'},
        ),
    ]
