# Generated by Django 2.2.16 on 2022-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20221018_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=50, verbose_name='Текст комментария'),
        ),
    ]
