# Generated by Django 2.2.9 on 2022-08-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
    ]
