# Generated by Django 2.2.9 on 2022-08-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_auto_20220821_1920"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Сообщество",
                "verbose_name_plural": "Сообщества",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="post.Group",
            ),
        ),
    ]
